apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: ott
spec:
  completions: 5
  parallelism: 2
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
