apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-cicd
  namespace: ott
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # you can also use ["*"]
