apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-cicd
  namespace: ott
rules:
- apiGroups: ["", "apps"]
  resources: ["ingresses","services", "configmaps", "persistentvolumeclaims", "deployments", "statefulsets", "pods", "replicasets" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["", "storage.k8s.io"]
  resources: ["serviceaccounts", "storageclasses"]
  verbs: ["get", "list"]
