apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb_sa-ott
  namespace: ott
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-ott
  namespace: ott

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb_ott_user1
  namespace: ott
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-cicd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cn=user1,ou=users,dc=myldap,dc=io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb_ott_ondal
  namespace: ott
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-cicd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cn=ondal,ou=users,dc=myldap,dc=io

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb_ott_sa-ott
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: sa-ott
  namespace: ott

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb_ott_user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crole-cicd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cn=user1,ou=users,dc=myldap,dc=io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb_ott_user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crole-cicd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cn=ondal,ou=users,dc=myldap,dc=io

