apiVersion: v1
kind: Config
clusters:
- name: flask-auth
  cluster:
    server: http://10.178.189.25:6000  # https://<ADDR>:<PORT> 형식
    insecure-skip-tls-verify: true  # tls 설정 disable
users:
- name: kube-apiserver
contexts:
- context:
    cluster: flask-auth
    user: kube-apiserver
  name: auth
current-context: auth