apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ott
  namespace: ott
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-ott-secret
  namespace: ott
  annotations:
    kubernetes.io/service-account.name: sa-ott
type: kubernetes.io/service-account-token
