apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: secondary
    app.kubernetes.io/instance: member
    app.kubernetes.io/name: mysql
  name: member-secondary
  namespace: ott
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: secondary
      app.kubernetes.io/instance: member
      app.kubernetes.io/name: mysql
  serviceName: member-secondary
  template:
    metadata:
      labels:
        app.kubernetes.io/component: secondary
        app.kubernetes.io/instance: member
        app.kubernetes.io/name: mysql
    spec:
      serviceAccount: sa-ott-mysql
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: secondary
                  app.kubernetes.io/instance: member
                  app.kubernetes.io/name: mysql
              namespaces:
              - ott
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        image: docker.io/bitnami/mysql:8.0.22-debian-10-r44
        imagePullPolicy: IfNotPresent
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MYSQL_REPLICATION_MODE
          value: slave
        - name: MYSQL_MASTER_HOST
          value: member-primary
        - name: MYSQL_MASTER_PORT_NUMBER
          value: "3306"
        - name: MYSQL_MASTER_ROOT_USER
          value: root
        - name: MYSQL_REPLICATION_USER
          value: replicator
        - name: MYSQL_MASTER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: member-dbsecret
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-replication-password
              name: member-dbsecret
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              password_aux="${MYSQL_MASTER_ROOT_PASSWORD:-}"
              if [[ -f "${MYSQL_MASTER_ROOT_PASSWORD_FILE:-}" ]]; then
                  password_aux=$(cat "$MYSQL_MASTER_ROOT_PASSWORD_FILE")
              fi
              mysqladmin status -uroot -p"${password_aux}"
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              password_aux="${MYSQL_MASTER_ROOT_PASSWORD:-}"
              if [[ -f "${MYSQL_MASTER_ROOT_PASSWORD_FILE:-}" ]]; then
                  password_aux=$(cat "$MYSQL_MASTER_ROOT_PASSWORD_FILE")
              fi
              mysqladmin status -uroot -p"${password_aux}"
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 512m
            memory: 1024Mi
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/mysql
          name: data
        - mountPath: /opt/bitnami/mysql/conf/mysql.cnf
          name: config
          subPath: mysql.cnf
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql
        name: config
      - name: data
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                app.kubernetes.io/component: secondary
                app.kubernetes.io/instance: member
                app.kubernetes.io/name: mysql
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi