apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ott-mysql
  namespace: ott

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb_ott_sa-ott-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: sa-ott-mysql
  namespace: ott

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb_sa-ott-mysql
  namespace: ott
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-ott-mysql
  namespace: ott

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ott-mysql-cm
  namespace: ott
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: ott
    app.kubernetes.io/name: mysql
data:
  my.cnf: |-

    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid

---

kind: Secret
apiVersion: v1
metadata:
  name: ott-mysql-secret
  namespace: ott
stringData:
  mysql-password: happy@cloud
  mysql-replication-password: happy@cloud
  mysql-root-password: happy@cloud
type: Opaque

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: ott
    app.kubernetes.io/name: mysql
  name: ott-primary
  namespace: ott
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: ott
      app.kubernetes.io/name: mysql
  serviceName: ott-primary
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: ott
        app.kubernetes.io/name: mysql
    spec:
      serviceAccount: sa-ott-mysql
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: primary
                  app.kubernetes.io/instance: ott
                  app.kubernetes.io/name: mysql
              namespaces:
              - ott
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        image: docker.io/bitnami/mysql:8.0.22-debian-10-r44
        imagePullPolicy: IfNotPresent
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: ott-mysql-secret
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: ott-mysql-secret
        - name: MYSQL_DATABASE
          value: ott
        - name: MYSQL_REPLICATION_MODE
          value: master
        - name: MYSQL_REPLICATION_USER
          value: replicator
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-replication-password
              name: ott-mysql-secret
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              password_aux="${MYSQL_ROOT_PASSWORD:-}"
              if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                  password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
              fi
              mysqladmin status -uroot -p"${password_aux}"
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              password_aux="${MYSQL_ROOT_PASSWORD:-}"
              if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                  password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
              fi
              mysqladmin status -uroot -p"${password_aux}"
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: 
          requests: 
            cpu: 256m 
            memory: 512Mi 
          limits: 
            cpu: 512m 
            memory: 1024Mi
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/mysql
          name: data
        - mountPath: /opt/bitnami/mysql/conf/my.cnf
          name: config
          subPath: my.cnf
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: ott-mysql-cm
        name: config
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: ott
        app.kubernetes.io/name: mysql
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: ott-primary
  namespace: ott
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: ott
    app.kubernetes.io/name: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
    protocol: TCP

