kind: PersistentVolume
apiVersion: v1
metadata:
  name: member-primary 
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: member 
    app.kubernetes.io/name: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.178.189.25
    path: /data/ott/member/primary  
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-member-primary-0
    namespace: ott

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: member-secondary-0
  labels:
    app.kubernetes.io/component: secondary
    app.kubernetes.io/instance: member
    app.kubernetes.io/name: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.178.189.25
    path: /data/ott/member/secondary-0  
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-member-secondary-0
    namespace: ott

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: member-secondary-1
  labels:
    app.kubernetes.io/component: secondary
    app.kubernetes.io/instance: member 
    app.kubernetes.io/name: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.178.189.25
    path: /data/ott/member/secondary-1  
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-member-secondary-1
    namespace: ott
