elasticsearchHosts: "http://elasticsearch-master:9200"

replicas: 1

kibanaConfig:
   kibana.yml: |
     elasticsearch:
       username: ${ELASTICSEARCH_USERNAME}
       password: ${ELASTICSEARCH_PASSWORD}

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

resources:
  requests:
    cpu: "512m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: kibana.169.56.70.201.nip.io
      paths:
        - path: /
