apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: probe-httpget
  namespace: ott
  labels:
    app: probe-httpget
spec:
  selector:
    matchLabels:
      app: probe-httpget
  replicas: 1
  serviceName: probe-httpget
  podManagementPolicy: Parallel
  template:
    metadata:
      name: probe-httpget
      labels:
        app: probe-httpget
    spec:
      serviceAccount: sa-ott
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: ""
      containers:
      - name: probe-httpget
        image: docker.io/hiondal/member:0.0.1
        imagePullPolicy: Always
        env:
        - name: service_port
          value: "3001"
        - name: PROFILE
          value: dev
        envFrom:
        - configMapRef:
            name: "member-cm"
        - secretRef:
            name: "member-secret"
        ports:
        - name: containerport
          containerPort: 3001
        resources:
          requests:
            cpu: 64m
            memory: 64Mi
          limits:
            cpu: 128m
            memory: 128Mi
        startupProbe:
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 30
          successThreshold: 1
        readinessProbe: 
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
          successThreshold: 1
        livenessProbe: 
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: data
          mountPath: /home/docker/data
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ott
          readOnly: true
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
