apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: probe-httpreq
  namespace: ott
  labels:
    app: probe-httpreq
spec:
  selector:
    matchLabels:
      app: probe-httpreq
  replicas: 3
  serviceName: probe-httpreq
  podManagementPolicy: Parallel
  template:
    metadata:
      name: probe-httpreq
      labels:
        app: probe-httpreq
    spec:
      serviceAccount: default
      containers:
      - name: probe-httpreq
        image: docker.io/hiondal/member:0.0.1
        imagePullPolicy: Always
        env:
        - name: service_port
          value: "3001"
        - name: PROFILE
          value: dev
        - name: ottmember_filepath
          value: data/members.properties
        ports:
        - name: containerport
          containerPort: 3001
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 256m
            memory: 256Mi
        startupProbe:
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 30
          successThreshold: 1
        readinessProbe: 
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
          successThreshold: 1
        livenessProbe: 
          httpGet:
            port: 3001
            path: /actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: data
          mountPath: /home/docker/data
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: probe-httpreq
          readOnly: true
      terminationGracePeriodSeconds: 5
      restartPolicy: Always

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: probe-httpreq
  labels:
    service: probe-httpreq
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/ott
    type: Directory
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: probe-httpreq
  namespace: ott
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      service: probe-httpreq

---

apiVersion: v1
kind: Service
metadata:
  name: probe-httpreq
  namespace: ott
spec:
  type: ClusterIP
  selector:
    app: probe-httpreq
  ports:
  - name: port1
    port: 3001
    targetPort: 3001

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "false"
  name: probe-httpreq
  namespace: ott
spec:
  rules:
  - host: probe-httreq.169.56.70.201.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: probe-httpreq
            port:
              number: 3001

