apiVersion: v1
kind: Service
metadata:
  name: member-headless
  namespace: ott
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: member
  ports:
  - name: port1
    port: 3001
    targetPort: 3001
