apiVersion: v1
kind: Service
metadata:
  name: recommend
  namespace: ott 
spec:
  type: NodePort
  selector:
    app: recommend
  ports:
  - name: port1
    port: 3002
    targetPort: 3002
    nodePort: 30002
