apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: ott
spec:
  containers:
  - name: curl
    image: curlimages/curl
    imagePullPolicy: Always
    tty: true
    args:
    - sh
  restartPolicy: OnFailure
  