apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: ott
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
    spec:
      serviceAccount: sa-ott
      containers:
      - name: busybox
        args:
        - sh
        tty: true
        image: docker.io/library/busybox:unstable
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 5