apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: ott
spec:
  replicas: 3
  serviceName: busybox
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      serviceAccount: sa-ott
      containers:
      - name: busybox
        args:
        - sh
        tty: true
        image: busybox
        imagePullPolicy: IfNotPresent