apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: ott
spec:
  replicas: 4
  serviceName: busybox
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: busybox
  updateStrategy:
    rollingUpdate:
      partition: 2 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
    spec:
      serviceAccount: sa-ott
      containers:
      - name: busybox
        args:
        - sh
        tty: true
        image: docker.io/library/busybox:unstable
        imagePullPolicy: IfNotPresent